name: Formula CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run brew style
        run: brew style Formula/foreman-server.rb
